### ISSUE TITLE
ik moet leren

### ISSUE THREAD

**Issue by WesselMH** [Studeeric/proj1#109]
ik kan niet stoppen met examens maken hij blijft door gaan

**Comment by Barmanturbo** [comment]
[afkickhulp nodig](https://www.bing.com/ck/a?!&&p=11b23324bf7f2f6aea2e67b5769a415b485cdb420308eeed8dc6aad66e9dc8d8JmltdHM9MTY0ODgxNzAyNSZpZ3VpZD1iYTllOGExMC0zZDdlLTQwMmYtYjY4YS03YWNkNmYxNDU5OGMmaW5zaWQ9NTE3Ng&ptn=3&fclid=5e8a8be0-b1b9-11ec-bd97-6e4cbacd8ef6&u=a1aHR0cHM6Ly93d3cuYWZraWNra2xpbmlla3dpanplci5ubC8_bXNjbGtpZD01ZThhOGJlMGIxYjkxMWVjYmQ5NzZlNGNiYWNkOGVmNg&ntb=1)

**Comment by Studeeric** [comment]
Gefixed als het goed is.
