### ISSUE TITLE
geen out of bounce bij keuze 6

### ISSUE THREAD

**Issue by WesselMH** [Studeeric/proj1#111]
je kan een hoger getal invoeren dan dat er examens zijn en hij blijft zeggen dat het examen niet gehaald is

**Comment by Barmanturbo** [comment]
i'mma fix this

**Comment by Justwouter** [comment]
*bounds
unless a trampoline is involved

**Comment by Barmanturbo** [comment]
should be fixed now

**Comment by Barmanturbo** [comment]
gefixt *behalve* als je 3 invult

**Comment by Studeeric** [comment]
Probleem is opgelost jonguh
