### ISSUE TITLE
Create class Exam

### ISSUE THREAD

**Issue by Studeeric** [Studeeric/proj1#14]
See UML.
Wijzigingen kunnen er evt aan plaatsvinden.
Let op dat elke nieuwe examen aan de arraylist moet worden toegevoegd.

**Comment by Justwouter** [comment]
Kunnen we Questions toevoegen aan een examen atm?

**Comment by Studeeric** [comment]
Vragen toegevoegd.
Nu het doen van een examen werkend krijgen.
