### ISSUE TITLE
keuze 6, loop maken 

### ISSUE THREAD

**Issue by WesselMH** [Studeeric/proj1#142]
als je een toets heb gekeken of je die gehaald hebt kan je niet door gaan met nog een toets opvragen. voor consistentie dit toe voegen dus dat die niet meteen naar hoofd menu gaat

**Comment by Studeeric** [comment]
Waarom werkt 3 zo raar?!!?! alle andere getallen werken goed maar 3 oppeens niet huhhh

**Comment by Studeeric** [comment]
Boom
