### ISSUE TITLE
In examens wisselen van A,B,C etc. naar 1,2,3

### ISSUE THREAD

**Issue by Justwouter** [Studeeric/proj1#147]
Letters kunnen niet opgeteld worden zonder external libs
Nummers kunnen dat wel waardoor we ze kunnen genereren ipv hardcoden

ook matched beter met de rest van de applicatie

oftewel, kunnen we letters naar nummers veranderen?

**Comment by Studeeric** [comment]
Ja van mij mag dat wel. Moet dat in savemanager of iets dergelijks gewijzigd worden?
Ook moeten we trouwens een paar "Ja/Nee" vragen maken..

**Comment by Justwouter** [comment]
Done
