### ISSUE TITLE
dubbelen bij opvragen welke toets iemand is geslaagd

### ISSUE THREAD

**Issue by WesselMH** [Studeeric/proj1#149]
nu kan je een toets meerdere malen maken en als je hem vaker haalt wordt die ook meerdere keren opgeslagen in de lijst met welke examens je hebt gehaald. niet dat het fout is want dan kan je zien hoe vaak je een toets opnieuw gehaald hebt, maar wilde even weten of dit de bedoeling was

**Comment by Justwouter** [comment]
How about: Het examen met de hoogste score komt in de kijst?

**Comment by Justwouter** [comment]
Gefixt door het examen niet toe te voegen als iemand het exeman al gehaal heeft
