### ISSUE TITLE
negatieve getallen hoofdmenu

### ISSUE THREAD

**Issue by WesselMH** [Studeeric/proj1#151]
ik dacht dat lucas hier mee bezig was geweest maar is denkt ergens vervallen of niet helemaal goed gegaan, maar je kan bij het hoofdmenu "-" voor je getal zetten en hij geeft geen fout bericht maar refresht gewoon het hele hoofd menu

**Comment by Barmanturbo** [comment]
refreshen komt door de switch statement. Zal ermee aan de slag gaan.

**Comment by Barmanturbo** [comment]
Should be fixed now door math.abs()

**Comment by Barmanturbo** [comment]
fixed
