### ISSUE TITLE
new student number hoger dan 10 cijfers

### ISSUE THREAD

**Issue by WesselMH** [Studeeric/proj1#152]
als je meer dan 10 cijfers invoert vind die dat je een string maakt ofzo dus geeft die de melding "Voer alleen cijfers in"

is er ergens een max voor de student nummer gezet?

**Comment by Kikkerslijm410** [comment]
Nee niet dat ik weet zou niet moeten gebeuren

**Comment by Barmanturbo** [comment]
take that @Kikkerslijm410
