### ISSUE TITLE
3 voor terug keren en niet 0 bij examen afnemen fout student nummer

### ISSUE THREAD

**Issue by WesselMH** [Studeeric/proj1#153]
als je bij de optie examen afnemen een verkeerd student nummer invoert krijg je netjes een menu van wat wil je doen maar overal is de optie terug 0 en hier is die 3. voor geliktheid zou die denkt ook 0 moeten zijn

ook als je 3 invoert ga je niet terug naar het hoofd menu

**Comment by WesselMH** [comment]
als je wel bijvoorbeeld 0 (of een ander getal dan er opties zijn) invoer komt de melding "Verkeerde optie. Ga terug naar main menu." maar hij gaat niet naar het hoofd menu

**Comment by Kikkerslijm410** [comment]
ik ga hiernaar kijken

**Comment by Justwouter** [comment]
Gefixt
