### ISSUE TITLE
negatief student nummer

### ISSUE THREAD

**Issue by WesselMH** [Studeeric/proj1#154]
![Knipsel](https://user-images.githubusercontent.com/93765122/161937298-a89b521c-42ce-4071-947a-074dc69a9750.PNG)
student:makeStudent:Eric:21146632
student:makeStudent:Lucas:21093830
student:makeStudent:Wessel:21046220
student:makeStudent:Burton:21035407
student:makeStudent:Wouter:21076367
student:makeStudent:Fat Albert Gomez:69420
student:makeStudent:qwe:-123
student:makeStudent:qwe:123

ik heb het voor elkaar gekregen om negatieve student nummers er in te krijgen maar hij gaf wel fout melding toen ik het deed

ik gaf eerst -123 
toen fout melding van mag niet negatief
ik gaf toen 123 maar hij heeft blijkbaar de -123 opgeslagen

**Comment by Barmanturbo** [comment]
Nu verandert het negatieve student nummers naar positieve student nummers voordat die dingen opslaat. ALs het een negatief studentnummer zou zijn, geeft die een bericht dat het is veranderd naar een positieve.

**Comment by Kikkerslijm410** [comment]
wat is hier veranderd want ik had dit al gefixed voordat het een issue was

**Comment by Barmanturbo** [comment]
ik heb Math.abs() gebruikt om de input heen om een positief getal te forceren

**Comment by Studeeric** [comment]
Is het niet het idee dat we deze dan uberhaupt niet op willen slaan?

**Comment by Barmanturbo** [comment]
monkey tests ¯\_ (ツ)_/¯ nu handelt die negatieve getallen alsof het een positief getal is. anyways, dit is nu definitief gefixt.

**Comment by Barmanturbo** [comment]
check pull #175 
should be fixed
