### ISSUE TITLE
File

### ISSUE THREAD

**Issue by Studeeric** [Studeeric/proj1#20]
Uitvogelen hoe je gegevens uitleest naar een file bij afsluiten en afleest vanuit een file bij opstarten.

**Comment by Justwouter** [comment]
-Lijstje met gegevens die opgeslagen moeten worden
-File format (Plain .txt, .json, .csv, .xml, etc)

**Comment by Justwouter** [comment]
Allright, De savefile werkt sinds #90. Voor de savefile gebruiken we de niet bestaande .Wdf als txt.   

De syntax is:
# comment
: separator
class/object:actie:var1:var2:var3 etc.
e.g.
student:makeNewStudent:Geraldt:21076654:rekenen == Nieuwe student met naam Geraldt, leerlingnummer 21... en hij heeft de toets rekenen gehaald.
rekenen:addQuestion:wat is 1 + 1?: A) 1: B) 4: C) 2: D) 6:C == voor questions is de 1e index _altijd_ de vraag en de laatste index _altijd_ het antwoord
