### ISSUE TITLE
Actual Issues

### ISSUE THREAD

**Issue by Justwouter** [Studeeric/proj1#44]
- In app moeten een aantal methods waarschijnlijk static worden
- SaveManager Schijnt soms te vergeten dat mensen Exams hebben gehaald

Gefixed:
- op App line 122 Exam.startExam() krijgt een exam mee terwijl er een Student gegeven moet worden
- Scanners crashen wanneer scanner.close() gebruikt wordt

**Comment by Barmanturbo** [comment]
Misschien moet er zowel een student als exam in meegegeven worden

**Comment by Barmanturbo** [comment]
Alle methodes in class App zijn static
