### ISSUE TITLE
Examen afnemen: Vragen netjes

### ISSUE THREAD

**Issue by Studeeric** [Studeeric/proj1#78]
Kijken of het mogelijk is om bij elke vraag van een examen een net leeg scherm te krijgen.
Waarbij er bij de opvolgende vraag je bovenaan alleen ziet hoeveel goed of fout je hebt. (Niet dat je meerdere vragen nog in je scherm hebt)

**Comment by Justwouter** [comment]
Call App.clearScreen voor de goed/fout print
